### ISSUE TITLE
Add SCS and CBD logos

### ISSUE THREAD

**Issue by icaoberg** [CBDatCMU/cbd-directory#2]
Add SCS and CBD logos to template.

* CMU SCS top left
* CMU CBD top right

create a new branch for this issue.

**Comment by uhq1** [comment]
Issue resolved by adding a header, changing theme of presentation to white background, also resizing images for affiliated faculty so that the heading doesn't go into the header.

[
![screen shot 2018-06-06 at 13 39 43](https://user-images.githubusercontent.com/22680399/41055433-52646e84-698f-11e8-8b01-428d78aece9d.png)
](url)

**Comment by uhq1** [comment]
Did the same for postdoctoral fellows
![screen shot 2018-06-06 at 13 45 45](https://user-images.githubusercontent.com/22680399/41055710-faeae04c-698f-11e8-82ea-e9ef21048a57.png)

**Comment by uhq1** [comment]
https://github.com/icaoberg/cbd-directory/pull/8
